import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900' ] });

export const metadata = {
  title: "Symbiote",
  description: "Generated by Zain Rehman Ansari",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={poppins.className}>
        <div className="h-full flex flex-col">
            <Header/>
          <div className="flex-grow ">
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
